# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SpiritMate MYOB Sync
version: "2.4.0"
slug: spiritmate_myob_sync
description: "Sync MYOB invoice emails to SpiritMate inventory (Firestore) with IMAP parsing and scheduled runs"
url: "https://github.com/Howy1972/spiritmate-homeassistant-addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  imap_host: ""
  imap_port: 993
  imap_user: ""
  imap_pass: ""
  imap_mailbox: "INBOX"
  from_exact: ""
  subject_prefix: ""
  label_processed: ""
  firestore_project_id: ""
  schedule_enabled: false
  schedule_cron: "0 2 * * *"
  log_level: "info"
schema:
  imap_host: str
  imap_port: int
  imap_user: str
  imap_pass: password
  imap_mailbox: str?
  from_exact: str
  subject_prefix: str
  label_processed: str?
  firestore_project_id: str
  schedule_enabled: bool
  schedule_cron: str
  log_level: list(debug|info|warning|error)
# Build locally (no prebuilt image)
ingress: true
ingress_port: 8099
panel_icon: mdi:cloud-sync
hassio_api: true
hassio_role: default
